from enum import IntEnum


class ErrorType(IntEnum):
    REQUIREMENTS_TXT_NEEDS_PYTHON = 0
    PIP_INSTALL_FAILED_AND_EXITED = 1
    PIP3_INSTALL_FAILED_AND_EXITED = 2
    SETUP_EGG_INFO_FAILED = 3
    PYTHON3_SETUP_EGG_INFO_FAILED = 4
    PIP_INSTALL_FAILED_TIMES = 5
    PIP3_INSTALL_FAILED_TIMES = 6
    PYTHON_SETUP_FAILED_EXITED = 7
    PYTHON3_SETUP_FAILED_EXITED = 8
    VIRTUAL_ENV_ERROR = 9
    PACKAGE_REQUIRES_PYTHON = 10
    PACKAGE_REQUIRES_DIFFERENT_PYTHON = 11
    SCRIPT_REQUIRES_PYTHON = 12
    PACKAGE_IN_REQ_TXT_NEEDS_PYTHON = 13
    IMPORT_ERROR = 14
    TYPE_ERROR = 15
    FLAKE_ERROR = 16
    MODULE_NOT_FOUND_ERROR = 17
    NO_MODULE_FOUND_ERROR = 18
    CYTHON_ERROR = 19
    COMMAND_NOT_FOUND_ERROR = 20

